spring:
  application:
    name: melior-and-movie

server:
  port: 8080

# Настройки TMDB API
tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    key: ${TMDB_API_KEY:your-api-key-here}  # можно задать через переменную окружения
    image-base-url: https://image.tmdb.org/t/p/w500

# Логирование
logging:
  level:
    root: INFO
    com.example.movieapp: DEBUG
    org.springframework.web.client.RestClient: DEBUG